rq_dashboard/blueprint.py
"""RQ Dashboard Flask Blueprint.

Uses the standard Flask configuration mechanism e.g. to set the connection
parameters to REDIS. To keep the documentation and defaults all in once place
the default settings must be loaded from ``rq_dashboard.default_settings`` e.g.
as done in ``scripts/rq_dashboard.py``.

RQ Dashboard does not contain any built-in authentication mechanism because

    1. it is the responsbility of the wider hosting app rather than a
       particular blueprint, and

    2. there are numerous ways of adding security orthogonally.

As a quick-and-dirty convenience, the command line invocation in
``scripts/rq_dashboard.py`` provides the option to require HTTP Basic Auth in a
few lines of code.

"""
from flask import Blueprint, current_app, url_for, render_template
from functools import wraps
from math import ceil
from redis import Redis, from_url
from rq import (
    Queue, Worker, cancel_job, requeue_job, get_failed_queue,
    push_connection, pop_connection)
import times


blueprint = Blueprint(
    'rq_dashboard',
    __name__,
    template_folder='templates',
    static_folder='static',
)


@blueprint.before_app_first_request
def setup_rq_connection():
    redis_url = current_app.config.get('REDIS_URL')
    if redis_url:
        current_app.redis_conn = from_url(redis_url)
    else:
        current_app.redis_conn = Redis(
            host=current_app.config.get('REDIS_HOST'),
            port=current_app.config.get('REDIS_PORT'),
            password=current_app.config.get('REDIS_PASSWORD'),
            db=current_app.config.get('REDIS_DB')
        )


@blueprint.before_request
def push_rq_connection():
    push_connection(current_app.redis_conn)


@blueprint.teardown_request
def pop_rq_connection(exception=None):
    pop_connection()


def jsonify(f):
    @wraps(f)
    def _wrapped(*args, **kwargs):
        from flask import jsonify as flask_jsonify
        try:
            result_dict = f(*args, **kwargs)
        except Exception as e:
            result_dict = dict(status='error')
            if current_app.config['DEBUG']:
                result_dict['reason'] = str(e)
                from traceback import format_exc
                result_dict['exc_info'] = format_exc()
        return flask_jsonify(**result_dict)
    return _wrapped


def serialize_queues(queues):
    return [
        dict(
            name=q.name,
            count=q.count,
            url=url_for('.overview', queue_name=q.name))
        for q in queues
    ]


def serialize_date(dt):
    if dt is None:
        return None
    return times.format(dt, 'UTC')


def serialize_job(job):
    return dict(
        id=job.id,
        created_at=serialize_date(job.created_at),
        enqueued_at=serialize_date(job.enqueued_at),
        ended_at=serialize_date(job.ended_at),
        origin=job.origin,
        result=job._result,
        exc_info=job.exc_info,
        description=job.description)


def remove_none_values(input_dict):
    return {k: v for (k, v) in input_dict.items() if v is not None}


def pagination_window(total_items, cur_page, per_page=5, window_size=10):
    all_pages = range(1, int(ceil(total_items / float(per_page))) + 1)
    result = all_pages
    if window_size >= 1:
        temp = min(
            len(all_pages) - window_size,
            (cur_page - 1) - int(ceil(window_size / 2.0))
        )
        pages_window_start = max(0, temp)
        pages_window_end = pages_window_start + window_size
        result = all_pages[pages_window_start:pages_window_end]
    return result


@blueprint.route('/', defaults={'queue_name': None, 'page': '1'})
@blueprint.route('/<queue_name>', defaults={'page': '1'})
@blueprint.route('/<queue_name>/<page>')
def overview(queue_name, page):
    if queue_name is None:
        # Show the failed queue by default if it contains any jobs
        failed = Queue('failed')
        if not failed.is_empty():
            queue = failed
        else:
            queue = Queue()
    else:
        queue = Queue(queue_name)

    return render_template(
        'rq_dashboard/dashboard.html',
        workers=Worker.all(),
        queue=queue,
        page=page,
        queues=Queue.all(),
        rq_url_prefix=url_for('.overview')
    )


@blueprint.route('/job/<job_id>/cancel', methods=['POST'])
@jsonify
def cancel_job_view(job_id):
    cancel_job(job_id)
    return dict(status='OK')


@blueprint.route('/job/<job_id>/requeue', methods=['POST'])
@jsonify
def requeue_job_view(job_id):
    requeue_job(job_id)
    return dict(status='OK')


@blueprint.route('/requeue-all', methods=['GET', 'POST'])
@jsonify
def requeue_all():
    fq = get_failed_queue()
    job_ids = fq.job_ids
    count = len(job_ids)
    for job_id in job_ids:
        requeue_job(job_id)
    return dict(status='OK', count=count)


@blueprint.route('/queue/<queue_name>/empty', methods=['POST'])
@jsonify
def empty_queue(queue_name):
    q = Queue(queue_name)
    q.empty()
    return dict(status='OK')


@blueprint.route('/queue/<queue_name>/compact', methods=['POST'])
@jsonify
def compact_queue(queue_name):
    q = Queue(queue_name)
    q.compact()
    return dict(status='OK')


@blueprint.route('/queues.json')
@jsonify
def list_queues():
    queues = serialize_queues(sorted(Queue.all()))
    return dict(queues=queues)


@blueprint.route('/jobs/<queue_name>/<page>.json')
@jsonify
def list_jobs(queue_name, page):
    current_page = int(page)
    queue = Queue(queue_name)
    per_page = 5
    total_items = queue.count
    pages_numbers_in_window = pagination_window(
        total_items, current_page, per_page)
    pages_in_window = [
        dict(number=p, url=url_for('.overview', queue_name=queue_name, page=p))
        for p in pages_numbers_in_window
    ]
    last_page = int(ceil(total_items / float(per_page)))

    prev_page = None
    if current_page > 1:
        prev_page = dict(url=url_for(
            '.overview', queue_name=queue_name, page=(current_page-1)))

    next_page = None
    if current_page < last_page:
        next_page = dict(url=url_for(
            '.overview', queue_name=queue_name, page=(current_page+1)))

    pagination = remove_none_values(
        dict(
            pages_in_window=pages_in_window,
            next_page=next_page,
            prev_page=prev_page
        )
    )

    offset = (current_page - 1) * per_page
    jobs = [serialize_job(job) for job in queue.get_jobs(offset, per_page)]
    return dict(name=queue.name, jobs=jobs, pagination=pagination)


@blueprint.route('/workers.json')
@jsonify
def list_workers():
    def serialize_queue_names(worker):
        return [q.name for q in worker.queues]

    workers = [
        dict(
            name=worker.name,
            queues=serialize_queue_names(worker),
            state=worker.get_state()
        )
        for worker in Worker.all()
    ]
    return dict(workers=workers)


@blueprint.context_processor
def inject_interval():
    interval = current_app.config.get('RQ_POLL_INTERVAL')
    return dict(poll_interval=interval)

rq_dashboard/templates/rq_dashboard/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1.0">
        <title>RQ dashboard</title>

        {# Le styles -#}
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" href="{{ url_for('rq_dashboard.static', filename='css/bootstrap.min.css') }}">
        <link href="{{ url_for('rq_dashboard.static', filename='css/main.css') }}" rel="stylesheet">
    </head>

    <body>
        
        {% include "rq_dashboard/navbar.html" %}
        
        {% if deprecation_options_usage %}
        <p class="alert-danger sticky-top" style="text-align: center;">
            You are using deprecated options, pay attention to --help or readme.md to update your settings!<br>
            {% for option in deprecation_options_usage %}
                option {{ option }} is deprecated<br>
            {% endfor %}
        </p>
        {% endif %}

        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <div id="confirmation-modal" class="modal fade">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Do you really want to <span id="confirmation-modal-action"></span>?</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="confirmation-modal-no" class="btn">No</button>
                        <button type="button" id="confirmation-modal-yes" class="btn btn-primary">Yes</button>
                    </div>
                </div>
            </div>
        </div>

        {% include "rq_dashboard/footer.html" %}
        <script src="{{ url_for('rq_dashboard.static', filename='js/jquery-3.4.1.min.js') }}" type="text/javascript"></script>
        <script src="{{ url_for('rq_dashboard.static', filename='js/underscore-umd-min.js') }}" type="text/javascript"></script>
        <script src="{{ url_for('rq_dashboard.static', filename='js/sugar-1.2.1.min.js') }}" type="text/javascript"></script>
        <script src="{{ url_for('rq_dashboard.static', filename='js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
        <script type="text/javascript">
            {% include "rq_dashboard/inline_js.html" %}
            {% block content_scripts %}{% endblock %}
        </script>


        
    </body>
</html>

rq_dashboard/templates/rq_dashboard/dashboard.html
{% extends "rq_dashboard/base.html" %}


{% block content %}
<div class="row" id="rq-instances-row" style="display: none">
    <div class="span12">
        <div class="section">
            <h1>RQ Instances</h1>
            <p class="intro">Select below the RQ instance that you want to observe.</p>
            <select id="rq-instances">
            </select>
        </div>
    </div>
</div>
<div class="row">
    <div class="span6">
        <div class="section">

            <h1>Queues <a id="queues-btn" href="#">(toggle)</a></h1>
            <p class="fixed intro">This list below contains all the registered queues with the number of jobs currently
                in the queue. Select a queue from above to view all jobs currently pending on the queue.</p>

            <table id="queues" class="table table-bordered">
                <thead>
                <tr>
                    <th>Queue</th>
                    <th class="narrow">Jobs</th>
                </tr>
                </thead>
                <tbody>
                <tr data-role="loading-placeholder">
                    <td colspan="2">Loading...</td>
                </tr>
                </tbody>
            </table>

            <script name="queue-row" type="text/template">
                <tr data-role="queue" <% if (d.name === 'failed' && d.count > 0) { %> class="failed"<% } %>>
                <td><i class="icon-inbox" style="opacity: .5;"></i> <a href="<%= d.url %>"><%= d.name %></a></td>
                <td class="narrow"><%= d.count %></td>
                </tr>
            </script>

            <script name="no-queues-row" type="text/template">
                <tr>
                    <td colspan="3">No queues.</td>
                </tr>
            </script>

        </div>
    </div>

    <div class="span6">
        <div class="section">

            <h1>Workers <a id="workers-btn" href="#">(toggle)</a></h1>

            <p id="workers-count" class="fixed intro">No workers registered!</p>

            <table id="workers" class="table table-bordered" style="display: none;">
                <thead>
                <tr>
                    <th style="width:48px">State</th>
                    <th>Worker</th>
                    <th>Queues</th>
                </tr>
                </thead>
                <tbody>
                <tr data-role="loading-placeholder">
                    <td colspan="3">Loading...</td>
                </tr>
                </tbody>
            </table>

            <script name="worker-row" type="text/template">
                <tr data-role="worker">
                    <td><i class="icon-<%= d.state %>" title="Job ID: <%= d.current_job.job_id %>&#013;&#010;Description: <% if (d.current_job.description){ %> <%- d.current_job.description %> <% } %>&#013;&#010;Created at: <%= d.current_job.created_at %>&#013;&#010;"></i></td>
                    <td <% if (d.version && d.python_version) { %>title ="RQ <%= d.version %> / Python <%= d.python_version %>" <% } %>><%= d.name %></td>
                    <td><%= d.queues.join(', ') %></td>
                </tr>
            </script>

            <script name="no-workers-row" type="text/template">
                <tr>
                    <td colspan="3">No workers.</td>
                </tr>
            </script>

        </div>
    </div>
</div>

<div class="row">
    <div class="span12">
        <div class="section">

            <h1>Jobs on <strong{% if queue.name == 'failed' %} class="failed"{% endif %}>{{ queue.name }}</strong></h1>
            <p class="intro">
                {% if queue.name != 'failed' %}
                <a href="{{ url_for('rq_dashboard.empty_queue', queue_name=queue.name) }}" id="empty-btn"
                   class="btn btn-danger btn-small" style="float: right" data-toggle="tooltip"
                   title="Remove all jobs from this queue (<b>destructive</b>)" data-html=true><i
                        class="icon-trash icon-white"></i> Empty</a>
                <a href="{{ url_for('rq_dashboard.compact_queue', queue_name=queue.name) }}" id="compact-btn"
                   class="btn btn-small" style="float: right; margin-right: 8px;" data-toggle="tooltip"
                   title="Remove all stale jobs from this queue (non-destructive)"><i class="icon-resize-small"></i>
                    Compact</a>
                {% else %}
                <a href="{{ url_for('rq_dashboard.requeue_all') }}" id="requeue-all-btn" class="btn btn-small"
                   style="float: right; margin-right: 8px;"><i class="icon-retweet"></i> Requeue All</a>
                This list below contains all the registered jobs on queue <strong>{{ queue.name }}</strong>, sorted by
                age (oldest on top).</p>
                {% endif %}

            <table id="jobs" class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th class="narrow">Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr data-role="loading-placeholder">
                    <td colspan="2">Loading...</td>
                </tr>
                </tbody>
            </table>

            <script name="job-row" type="text/template">
                <tr data-role="job" data-job-id="<%= d.id %>">
                    <td>
                        <i class="icon-file" style="opacity: .5;"></i>
                        <span class="description"><%= $('<div/>').text(d.description).html() %></span>
                        <% if (d.exc_info) { %>
                        <span class="origin">from <strong><%= d.origin %></strong></span>
                        <% } %>
                        <div class="job_id"><%= d.id %></div>
                        <% if (d.exc_info) { %>
                        <span class="end_date">Failed <%= d.ended_at %></span>
                        <pre class="exc_info"><%= $('<div/>').text(d.exc_info).html() %></pre>
                        <% } %>
                    </td>
                    <td><span class="creation_date"><%= d.created_at %></span></td>
                    <td class="actions narrow">
                        <% if (d.exc_info) { %>
                        <a href="#" data-role="requeue-job-btn" class="btn btn-small"><i class="icon-retweet"></i>
                            Requeue</a>
                        <% } %>
                        <a href="#" data-role="cancel-job-btn" class="btn btn-small"><i class="icon-remove"></i> Cancel</a>
                    </td>
                </tr>
            </script>

            <script name="no-jobs-row" type="text/template">
                <tr>
                    <td colspan="3">No jobs.</td>
                </tr>
            </script>

            <div id="page-selection" class="pagination pagination-centered">
                <ul>
                </ul>
            </div>

            <script name="first-page-link" type="text/template">
                <li><a href="<%= url %>">&laquo;</a></li>
            </script>

            <script name="no-previous-page-link" type="text/template">
                <li class="disabled"><a href="#">&lsaquo;</a></li>
            </script>

            <script name="previous-page-link" type="text/template">
                <li><a href="<%= url %>">&lsaquo;</a></li>
            </script>

            <script name="page-link" type="text/template">
                <li><a href="<%= url %>"><%= number %></a></li>
            </script>

            <script name="next-page-link" type="text/template">
                <li><a href="<%= url %>">&rsaquo;</a></li>
            </script>

            <script name="no-next-page-link" type="text/template">
                <li class="disabled"><a href="#">&rsaquo;</a></li>
            </script>

            <script name="last-page-link" type="text/template">
                <li><a href="<%= url %>">&raquo;</a></li>
            </script>

        </div>
    </div>
</div>
<div class="row">
    <div class="span12">
        <div class="section">
          {%- set url = request.args.get("url") -%}
          <p class="intro"><a href="{{ url or '/' }}" id="home-btn" class="btn btn-small" style="float: left"><i
              class="icon-arrow-left"></i> {{'Back' if url else 'Home'}}</a></p>
        </div>
    </div>
</div>


{% endblock %}

{% block footer %}

<footer>
    <a href="https://github.com/Parallels/rq-dashboard">RQ-dashboard</a><span class="text-white"> version: {{ rq_dashboard_version }}</span><br>
    <a href="http://python-rq.org">Python RQ</a><span class="text-white"> version: {{ rq_version }}</span>
</footer>

{% endblock %}


{% block inline_js %}
var POLL_INTERVAL = {{ poll_interval }};
{% include "rq_dashboard/dashboard.js" with context %}
{% endblock %}

rq_dashboard/templates/rq_dashboard/footer.html
<footer class="footer-text">
    <span class="col-6">
        <a href="https://github.com/Parallels/rq-dashboard">RQ-dashboard</a><span> version: {{ rq_dashboard_version }}
    </span>
    <span class="col-6">
        <a href="http://python-rq.org">Python RQ</a><span> version: {{ rq_version }}
    </span>
</footer>

rq_dashboard/templates/rq_dashboard/jobs.html
{% extends "rq_dashboard/base.html" %}

{% block content %}

<div class="section">

    <div class="input-group" id="filter-form">
        <div class="input-group-prepend">
            <span class="input-group-text">Queue:</span>
        </div>
        <input class="form-control" list="queues_list" id="select-queue" title="Queue name" value="{{ queue.name }}">
            <datalist id="queues_list">
                {% for selected_queue in queues %}
                <option value="{{ selected_queue.name }}">
                {% endfor %}
            </datalist>
        <div class="input-group-prepend input-group-append">
            <span class="input-group-text">Registry:</span>
        </div>
        <select class="custom-select" id="select-registry" title="Registry name">
            <option {% if registry_name == 'queued' %} selected {% endif %}>queued</option>
            <option {% if registry_name == 'scheduled' %} selected {% endif %}>scheduled</option>
            <option {% if registry_name == 'deferred' %} selected {% endif %}>deferred</option>
            <option {% if registry_name == 'started' %} selected {% endif %}>started</option>
            <option {% if registry_name == 'finished' %} selected {% endif %}>finished</option>
            <option {% if registry_name == 'failed' %} selected {% endif %}>failed</option>
            <option {% if registry_name == 'canceled' %} selected {% endif %}>canceled</option>
        </select>
        <div class="input-group-prepend input-group-append">
            <span class="input-group-text">Sort Order:</span>
        </div>
        <select class="custom-select" id="select-sort-order" title="Job Sort Order">
            <option {% if order == 'asc' %} selected {% endif %} value="asc">Ascending</option>
            <option {% if order == 'dsc' %} selected {% endif %} value="dsc">Descending</option>
        </select>
    </div>

    <p class="intro">
        {% if enable_delete %}
        <a href="{{ url_for('rq_dashboard.empty_queue', queue_name=queue.name, registry_name=registry_name) }}" id="empty-btn"
            class="btn btn-outline-danger btn-sm" style="float: right" data-toggle="tooltip"
            title="Remove all jobs from this queue (<b>destructive</b>)" data-html=true>Empty queue</a>
        {% endif %}
        {% if registry_name == 'queued' %}
        <a href="{{ url_for('rq_dashboard.compact_queue', queue_name=queue.name) }}" id="compact-btn"
            class="btn btn-outline-success btn-sm" style="float: right; margin-right: 8px;" data-toggle="tooltip"
            title="Remove all stale jobs from this queue (non-destructive)">Compact</a>
        {% endif %}
        {% if registry_name == 'failed' %}
        <a href="{{ url_for('rq_dashboard.requeue_all', queue_name=queue.name) }}" id="requeue-all-btn" class="btn btn-outline-warning btn-sm"
            style="float: right; margin-right: 8px;">Requeue All</a>
        {% endif %}
        This list below contains all the queued jobs on queue <strong>{{ queue.name }}</strong>.</p>

        <div class="table-responsive">
            <table id="jobs" class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th class="narrow">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr data-role="loading-placeholder">
                        <td colspan="3">Loading...</td>
                    </tr>
                </tbody>
            </table>
        </div>

    <script name="job-row" type="text/template">
        <tr data-role="job" data-job-id="<%= d.id %>">
            <td>
                <span class="description ellipsify"><%= $('<div/>').text(d.description).html() %></span>
                <div class="job_id"><a href="<%= url_for_single_job_view(d.id) %>"><%= d.id %></a></div>
                <% if (d.exc_info) { %>
                <span class="end_date">Failed <%= d.ended_at %></span>
                <pre class="exc_info"><%= $('<div/>').text(d.exc_info).html() %></pre>
                <% } %>
            </td>
            <td><span class="creation_date"><%= d.created_at %></span></td>
            <td class="actions narrow">
                <% if (d.exc_info) { %>
                <a href="#" data-role="requeue-job-btn" class="btn btn-outline-warning btn-sm btn-block">Requeue</a>
                <% } %>
                {% if enable_delete %}
                <a href="#" data-role="delete-job-btn" class="btn btn-outline-danger btn-sm">Delete</a>
                {% endif %}
            </td>
        </tr>
    </script>

    <script name="no-jobs-row" type="text/template">
        <tr>
            <td colspan="3">No jobs.</td>
        </tr>
    </script>

    <span class="input-group" style="">
        <span class="input-group-prepend">
            <div class="input-group-text">On page:</div>
        </span>
        <span class="input-group-append">
            <input title="Jobs per page" class="form-control" type="number" id="select-per-page" min="1" max="200" value="{{ per_page }}">
        </span>
    </span>
    <br />
    <div id="page-selection" class="pagination">
        <ul class="pagination"></ul>
    </div>

    <script name="first-page-link" type="text/template">
        <li class="page-item"><a class="page-link" href="<%= url %>">&laquo;</a></li>
    </script>

    <script name="no-previous-page-link" type="text/template">
        <li class="page-item disabled"><a class="page-link" href="#">&lsaquo;</a></li>
    </script>

    <script name="previous-page-link" type="text/template">
        <li class="page-item"><a class="page-link" href="<%= url %>">&lsaquo;</a></li>
    </script>

    <script name="page-link" type="text/template">
        <li class="page-item"><a class="page-link" href="<%= url %>"><%= number %></a></li>
    </script>

    <script name="next-page-link" type="text/template">
        <li class="page-item"><a class="page-link" href="<%= url %>">&rsaquo;</a></li>
    </script>

    <script name="no-next-page-link" type="text/template">
        <li class="page-item disabled"><a class="page-link" href="#">&rsaquo;</a></li>
    </script>

    <script name="last-page-link" type="text/template">
        <li class="page-item"><a class="page-link" href="<%= url %>">&raquo;</a></li>
    </script>

    <script name="no-last-page-link" type="text/template">
        <li class="page-item disabled"><a class="page-link" href="<%= url %>">&raquo;</a></li>
    </script>

</div>

{% endblock %}

{% block content_scripts %}
    {% include "rq_dashboard/scripts/jobs.js" %}
{% endblock %}

rq_dashboard/templates/rq_dashboard/jobs_table.html
{% macro render_html(queue_name, state_name, newest_top) -%}

<div class="row" id="{{ state_name }}-jobs-table">
    <div class="span12">
      <div class="section">
            <h1>{% if queue_name != 'failed' %}{{ state_name }}{% endif %} jobs on 
              <strong>{{ queue_name }} <span class="job-count"></span></strong>
            </h1>
            <p class="intro">
                  {% if state_name == 'finished' %}
                  <a href="{{ url_for('rq_dashboard.delete_all_job_view', queue_name=queue_name, state='finished') }}" id="empty-finished-jobs-btn" 
                         class="btn btn-danger btn-small" style="float: right" data-toggle="tooltip"
                         title="Remove all finished jobs (<b>destructive</b>)" data-html=true><i
                         class="icon-trash icon-white"></i> Empty</a>
                  {% elif state_name == 'running' %}
                  <a href="{{ url_for('rq_dashboard.cancel_all_job_view', queue_name=queue_name, state='running') }}" 
                           id="cancel-all-running-job-btn"
                           class="btn btn-danger btn-small" style="float: right" data-toggle="tooltip"
                           title="Cancel all running jobs from this queue (<b>destructive</b>)" 
                           data-html=true><i class="icon-trash icon-white"></i> Cancel ALL</a>
                  {% elif state_name == 'pending' %}
                  <a href="{{ url_for('rq_dashboard.empty_queue', queue_name=queue_name) }}" id="empty-pending-jobs-btn"
                           class="btn btn-danger btn-small" style="float: right" data-toggle="tooltip"
                           title="Remove all jobs from this queue (<b>destructive</b>)" data-html=true><i
                           class="icon-trash icon-white"></i> Empty</a>

                      <a href="{{ url_for('rq_dashboard.compact_queue', queue_name=queue_name) }}" id="compact-btn"
                           class="btn btn-small" style="float: right; margin-right: 8px;" data-toggle="tooltip"
                           title="Remove all stale jobs from this queue (non-destructive)"><i class="icon-resize-small"></i>
                            Compact</a>

                      <a href="{{ url_for('rq_dashboard.requeue_all') }}" id="requeue-all-btn" class="btn btn-small"
                            style="float: right; margin-right: 8px;"><i class="icon-retweet"></i> Requeue All</a>
                  {% endif %}

                  This list below contains all the registered jobs on queue <strong>{{ queue_name }}</strong>, sorted by
                  age ({% if newest_top %}newest {% else %}oldest {% endif %} on top).</p>

            <table id="{{ state_name }}-jobs" class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th class="narrow">Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr data-role="loading-placeholder">
                    <td colspan="2">Loading...</td>
                </tr>
                </tbody>
            </table>

            <script name="{{ state_name }}-jobs-row" type="text/template">
                <tr data-role="job" data-job-id="<%= d.id %>">
                    <td>
                        <i class="icon-file" style="opacity: .5;"></i>
                        <span class="description"><%= $('<div/>').text(d.description).html() %></span>
                        <% if (d.exc_info) { %>
                        <span class="origin">from <strong><%= d.origin %></strong></span>
                        <% } %>

                        <div class="job_id"><%= d.id %></div>
                        <% if (d.exc_info) { %>
                        <span class="end_date">Failed <%= d.ended_at %></span>
                        <pre class="exc_info" style="display:none"><%= $('<div/>').text(d.exc_info).html() %></pre>
                        <% } %>
                    </td>
                    <td><span class="creation_date"><%= d.created_at %></span></td>
                    <td class="actions narrow">
                        {% if state_name != 'running' %}
                          <a href="#" data-role="requeue-{{ state_name }}-job-btn" 
                              class="btn btn-small"><i class="icon-retweet"></i>Requeue</a>
                        {% endif %}
                        <a href="#" data-role="cancel-{{ state_name }}-job-btn" class="btn btn-small"><i class="icon-remove"></i> Cancel</a>
                    </td>
                </tr>
            </script>

            <script name="no-{{ state_name }}-jobs-row" type="text/template">
                <tr>
                    <td colspan="3">No jobs.</td>
                </tr>
            </script>

            <div id="{{ state_name }}-jobs-page-selection" class="pagination pagination-centered">
                <ul>
                </ul>
            </div>

            <script name="first-page-link" type="text/template">
                <li><a href="<%= url %>">&laquo;</a></li>
            </script>

            <script name="no-previous-page-link" type="text/template">
                <li class="disabled"><a href="#">&lsaquo;</a></li>
            </script>

            <script name="previous-page-link" type="text/template">
                <li><a href="<%= url %>">&lsaquo;</a></li>
            </script>

            <script name="page-link" type="text/template">
                <li><a href="<%= url %>"><%= number %></a></li>
            </script>

            <script name="next-page-link" type="text/template">
                <li><a href="<%= url %>">&rsaquo;</a></li>
            </script>

            <script name="no-next-page-link" type="text/template">
                <li class="disabled"><a href="#">&rsaquo;</a></li>
            </script>

            <script name="last-page-link" type="text/template">
                <li><a href="<%= url %>">&raquo;</a></li>
            </script>
        </div>
    </div>
</div>

{%- endmacro %}